export const Users = [
  {
    id: 1,
    profilePicture: "profile/1.png",
    username: "Shubham Singh",
  },
  {
    id: 2,
    profilePicture: "profile/2.jpeg",
    username: "Anil Japrel",
  },
  {
    id: 3,
    profilePicture: "profile/3.jpeg",
    username: "Ashish Poudel",
  },
  {
    id: 4,
    profilePicture: "profile/4.jpeg",
    username: "Ant Man",
  },
  {
    id: 5,
    profilePicture: "profile/5.jpeg",
    username: "Thor",
  },
  {
    id: 6,
    profilePicture: "profile/6.jpeg",
    username: "Iron Man",
  },
  {
    id: 7,
    profilePicture: "profile/7.jpeg",
    username: "Captain America",
  },
  {
    id: 8,
    profilePicture: "profile/8.jpeg",
    username: "Hawkey",
  },
  {
    id: 9,
    profilePicture: "profile/9.jpeg",
    username: "Black Panther",
  },
  {
    id: 10,
    profilePicture: "profile/5.jpeg",
    username: "Black Widow",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/12.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "posts/13.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/14.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "posts/15.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "posts/16.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "posts/17.png",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/12.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "posts/13.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "posts/16.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "posts/17.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
